create database data_analysis_project;
use data_analysis_project;
select * from customer_behaviour_analysis;

-- Business Insights Questions

ALTER TABLE customer_behaviour_analysis RENAME COLUMN `customer ID` TO customer_id;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Age` TO age;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Gender` TO gender;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Item Purchased` TO item_purchased;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Category` TO category;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Purchase Amount (USD)` TO purchase_amount_usd;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Location` TO location;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Size` TO size;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Color` TO color;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Season` TO season;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Review Rating` TO review_rating;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Subscription Status` TO subscription_status;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Shipping Type` TO shipping_type;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Discount Applied` TO discount_applied;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Previous Purchases` TO previous_purchases;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `Payment Method` TO payment_method;
ALTER TABLE customer_behaviour_analysis RENAME COLUMN `frequency_of_purchases` TO frequency_of_purchases;

-- 1. Which category generates highest revenue?

SELECT 
    Category, 
    ROUND(SUM(purchase_amount_usd), 2) AS highest_revenue
FROM customer_behaviour_analysis
GROUP BY Category
ORDER BY highest_revenue DESC;

-- 2 Are discounts actually increasing purchase value?

select  discount_applied,
 ROUND(SUM(purchase_amount_usd), 2) AS total_revenue,
 ROUND(avg(purchase_amount_usd), 2) AS avg_purchase
FROM customer_behaviour_analysis
GROUP BY discount_applied;

-- 3. What is the total revenue generated by male and female customer ? 
select 
	gender,
	round(sum(purchase_amount_usd),2) as highest_revenue
FROM customer_behaviour_analysis
group by gender
order by highest_revenue desc;

-- 4. Which customer used a discount but still spent more then the average purchase amount ?

SELECT 
    customer_id,
    purchase_amount_usd,
    discount_applied
FROM customer_behaviour_analysis
WHERE discount_applied = 'Yes'
AND purchase_amount_usd > (
    SELECT AVG(purchase_amount_usd) 
    FROM customer_behaviour_analysis
)
ORDER BY purchase_amount_usd DESC
LIMIT 10;

-- 5. Which are the top/bottom 5 products with the highest average review rating.
select
	item_purchased,
    round(avg(review_rating),2) as avg_ratings
from customer_behaviour_analysis
group by item_purchased
order by avg_ratings desc
limit 5;

select
	item_purchased,
    round(avg(review_rating),2) as avg_ratings
from customer_behaviour_analysis
group by item_purchased
order by avg_ratings asc
limit 5;

-- 6. Average purchase: Standard vs Express shipping
select 
	shipping_type,
    count(distinct customer_id) as order_placed,
    round(avg(purchase_amount_usd),2) as  avg_purchase,
    round(sum(purchase_amount_usd),2)  as revenue
from customer_behaviour_analysis
-- --WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
ORDER BY revenue DESC;

-- 7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(*) AS total_users,
    ROUND(AVG(purchase_amount_usd), 2) AS avg_revenue,
    ROUND(SUM(purchase_amount_usd), 2) AS total_revenue
FROM customer_behaviour_analysis
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- 8. Top 5 products with highest discount usage %
select
	item_purchased,
    count(item_purchased) as total_number_of_times_sold,
    count(case when discount_applied='Yes' then 1 end)  as Number_of_times_sold_when_disocunt_applied,
    COUNT(CASE WHEN discount_applied='Yes' THEN 1 END) *100.0 / COUNT(*) AS discount_percent
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY discount_percent DESC
limit 5;

-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase
SELECT 
	CASE 
		WHEN previous_purchases= '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15  THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count
FROM customer_behaviour_analysis
GROUP BY CASE 
		WHEN previous_purchases= '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15  THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END;

-- 10. What are the top 3 most purchased products within each category ?
WITH CTE AS 
(
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS most_purchased
    FROM customer_behaviour_analysis
    GROUP BY category, item_purchased
),
Ranked AS
(
    SELECT *,
           RANK() OVER (PARTITION BY category ORDER BY most_purchased DESC) AS RNK
    FROM CTE
)
SELECT *
FROM Ranked
WHERE RNK <= 3
limit 3;

-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
SELECT
	CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
        END AS customer_type,
	subscription_status,
	COUNT(*) AS customer_count,
	COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
										WHEN previous_purchases > 5 THEN 'Repeat Buyers'
										ELSE 'Normal Buyers'
									END
									) AS percents

FROM customer_behaviour_analysis
GROUP BY CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END,subscription_status;
    
-- 12. What is the revenue contribution of each age group ? 
SELECT 
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END AS age_group,
	ROUND(SUM(purchase_amount_usd),2) AS total_revenue
FROM customer_behaviour_analysis
GROUP BY CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END
	ORDER BY total_revenue DESC;




